name: APK builder

on:
  workflow_dispatch

jobs:
  generate-apk:
    name: Generate apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Generate apk
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: build-output
          path: app/build/outputs/apk/debug/app-debug.apk
